import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { LineProvider } from "../providers/line";

const prompt = Prompt({ subsets: ["thai"], weight: ["300", "400", "600"] });

export const metadata: Metadata = {
  title: "แม่หมอมี่มี่.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LineProvider>
        <body
          className={`${prompt.className} antialiased bg-gradient-to-br from-base-300 via-base-100 to-base-300`}
        >
          {children}
        </body>
      </LineProvider>
    </html>
  );
}
